#import "@tgin/main/iblock/gql/fragment/ElementProp.gql"

fragment ProductElement on ProductElement {
    ID
    ACTIVE
    ACTIVE_FROM(format: "default")
    CODE
    NAME
    URL
    IBLOCK_ID

    PROPS(detail: $elementDetail) {
        ...ElementProp
    }

    DETAIL_TEXT @include(if: $elementDetail)
    DETAIL_IMAGE @include(if: $elementDetail) {
        SRC
    }

    PREVIEW_TEXT
    LIST_IMAGE {
        SRC
    }

    ACTIONS

    MEASURE {
        NAME
        RATIO
    }
    PRICE {
        DISCOUNTED
        PRICE
        DISCOUNT_PERCENT
    }
    SECTIONS {
        ID
        NAME
    }
    PATH @include(if: $elementDetail) {
        ID
        NAME
        CODE
        URL
    }
    FLAGS {
        NAME
        COLOR
    }
    CATALOG_AVAILABLE
    CATALOG_CAN_BUY
    META {
        TITLE
        DESCRIPTION
        KEYWORDS
    }
}

