#import "../fragment/EduEpguDictionaryTerm.gql"
#import "@tgin/main/graphql/fragment/QueryInfo.gql"

query(
   $filter: JSON,
   $nav: QueryInputNav
) {
   res: edu_epgu_dictionary_term_listRecordset(filter: $filter, nav: $nav) {
     info {
       ...QueryInfo
     }
     nodes {
       ...EduEpguDictionaryTerm
     }
   }
}


