#import "../fragment/EduEge.gql"
#import "@tgin/main/graphql/fragment/QueryInfo.gql"

query(
   $filter: JSON,
   $nav: QueryInputNav
) {
   res: edu_ege_admin_listRecordset(filter: $filter, nav: $nav) {
     info {
       ...QueryInfo
     }
     nodes {
       ...EduEge
     }
   }
}


