#import "./ElementProp.gql"

fragment Element on Element {
    ID
    ACTIVE
    ACTIVE_FROM(format: "default")
    CODE
    NAME
    URL
    PREVIEW_TEXT
    LIST_IMAGE {
        SRC
    }
    ACTIONS
    DETAIL_TEXT @include(if: $elementDetail)
    DETAIL_IMAGE @include(if: $elementDetail) {
        SRC
    }
    META @include(if: $elementDetail) {
        TITLE
        DESCRIPTION
        KEYWORDS
    }
    PROPS(detail: $elementDetail) {
        ...ElementProp
    }
}

