#import "@tgin/main/graphql/fragment/QueryInfo.gql"
#import "../fragment/PaycardAdmin.gql"

query(
    $filter: PaycardFilter,
    $where: Json,
    $nav: QueryNavInput
) {
    res: sale_admin_paycard_recordset(
        filter: $filter,
        where: $where,
        nav: $nav
    ) {
        info {
            ...QueryInfo
        }
        nodes {
            ...PaycardAdmin
        }
    }
}


