#import "../fragment/EduInstitute.gql"
#import "@tgin/main/graphql/fragment/QueryInfo.gql"

query(
   $filter: JSON,
   $nav: QueryInputNav
) {
   res: edu_institute_admin_listRecordset(filter: $filter, nav: $nav) {
     info {
       ...QueryInfo
     }
     nodes {
       ...EduInstitute
     }
   }
}


