#import "./EduOrderState.gql"
#import "./../../orderType/fragment/EduOrderType.gql"
#import "./EduOrderApplication.gql"
#import "./EduOrderStepStatus.gql"
#import "./EduOrderAchievement.gql"
#import "~module/file/gql/fragment/File.gql"
#import "~module/edu-org/modules/doc/gql/fragment/EduDoc.gql"
#import "~module/edu-org/modules/doc/gql/fragment/EduDocRole.gql"
#import "~module/edu-org/modules/app/gql/fragment/EduApp.gql"
#import "~module/edu-org/modules/app-group/gql/fragment/EduAppGroup.gql"
#import "~module/edu-org/modules/abit-test/gql/fragment/AbitTest.gql"

fragment EduOrder on EduOrder {
    _id
    id
    nid
    uid
    userId
    regnum
    ratingId
    fio
    snils
    passport

    podldocAny
    podldoc
    podldocEpgu
    podldocEpguUpdated
    podldocEpguRecieved
    podldocEpguCanceled

    user {
        _id
        nid
        email
    }
    sendDate

    eduType
    eduTypeSlug
    eduTypeAppsLimit
    eduLevels

    cordersource
    ordersourceName

    cfacComputed

    cinstitute
    institute {
        id
        name
        phone
        email
    }

    anket {
        status {
            ...EduOrderStepStatus
        }
        personal
        education
        benefits
        entrance {
            schoolCertificateBall
            achievements {
                ...EduOrderAchievement
            }
            specialNeeds
            targetHave
            targetOrganization
            targetDogovor
            subjects {
                _id
                subject
                score
                status
                year
                checked
                subjectDoc {
                    name
                }
            }
        }
    }

    applications {
        status {
            ...EduOrderStepStatus
        }
        items {
            ...EduOrderApplication
        }
    }

    upload
    send

    allFiles

    files {
        ...File
        children {
            ...File
        }
    }

    createAt
    updateAt

    stepsInfo
    messages
    chat

    state {
        ...EduOrderState
    }

    orderType {
        ...EduOrderType
    }

    operator {
        firstName
        lastName
    }

    docs {
        ...EduDoc
    }

    appGroups {
        ...EduAppGroup
    }

    tests {
        ...AbitTest
    }

    actions
    perms

    docsRoles {
        ...EduDocRole
    }

    citizenTypeName

    ais {
        aisId
        state
    }

    phone
    email
    prevEduLevelName

    firstApp {
        _id
        nid
        priority
        statusId
        statusTitle
        competitionId
        cadmission
        cfac
        fac {
            name
        }
        competition {
            name
            csource
            admission {
                abbr
                name
                direct_name
            }
        }
    }

    portedStatus
    portedStatusInfo {
        code
        titleClient
        titleAdmin
        bgColor
        textColor
        color
        index
        canEdit
        selectable
    }

    epgu {
        guid
    }

    fis {
        exportSuccessDate
    }

    decreeNid
    decree {
        name
    }

    fis {
        exported
        exportedSuccessDate
    }

}

