#import "@tgin/main/iblock/gql/fragment/Element.gql"
#import "@tgin/main/graphql/fragment/QueryInfo.gql"

query(
    $filter: ElementFilter,
    $nav: QueryNavInput = {},
    $elementDetail: Boolean = false
)
{
    res: banner_elements(filter: $filter, nav: $nav) {
        nodes {
            ...Element
        }
        info {
            ...QueryInfo
        }
    }
}
