query(
    $filter: OrderFilter,
    $where: Json,
    $nav: QueryNavInput
) {
    res: sale_admin_order_basket_items(
        filter: $filter,
        where: $where,
        nav: $nav
    ) {
        ID
        NAME
        ORDER_ID
        PRODUCT_ID
        QUANTITY
        PRICE
        PRICE_BASE
        FINAL_PRICE
        FINAL_PRICE_BASE
        MEASURE_NAME
        COMMENT

        ELEMENT {
            ID
            NAME
            IBLOCK_SECTION_ID

            PARENT {
                ROOT_SECTION {
                    ID
                    NAME
                }
                SECTION {
                    ID
                    NAME
                }
            }
            ROOT_SECTION {
                ID
                NAME
            }
            SECTION {
                ID
                NAME
            }
        }

        ORDER {
            ID
            IS_PAID
            DATE_PAYED

            BUYER_NAME
            CONTRACT_NUM
            EDU_GROUP_NUM
            STUDENT_FIO
        }
    }
}


