#import "../../../core/gql/product/fragments/ProductSectionBase.gql"
#import "../../../core/gql/product/fragments/ProductElement.gql"

query(
    $filter: ProductSectionFilter,
    $elementDetail: Boolean = false
)
{
    res: catalog_constructor(filter: $filter) {
        ...ProductSectionBase
        PROPS {
            CODE
            VAL
        }
        CHILDREN {
            ...ProductSectionBase
            PROPS {
                CODE
                VAL
            }
            ELEMENTS {
                ...ProductElement
            }
        }
    }
}
