#import "@tgin/review/core/gql/fragments/Review.gql"

query(
    $filter: ReviewElementFilter,
    $nav: QueryNavInput = {},
    $elementInclude: Boolean = true,
    $elementDetail: Boolean = false
)
{
    res: review_pub_list(filter: $filter, nav: $nav) {
        ...Review
    }
}
