#import "@tgin/review/core/gql/fragments/Review.gql"

query(
    $filter: ReviewElementFilter,
    $elementInclude: Boolean = false,
    $elementDetail: Boolean = true
)
{
    res: review_pub_user_single(filter: $filter) {
        ...Review
        CHILDREN {
            ...Review
        }
    }
}
