#import "@tgin/review/core/gql/fragments/Review.gql"

query(
    $filter: ReviewElementFilter,
    $nav: QueryNavInput = {},
    $elementInclude: Boolean = false,
    $elementDetail: Boolean = false
)
{
    res: review_pub_user_list(filter: $filter, nav: $nav) {
        ...Review
        CHILDREN {
            ...Review
        }
    }
}
