#import "../fragment/Entity.gql"
#import "@tgin/main/graphql/fragment/QueryInfo.gql"

query(
   $nav: QueryNavInput,
   $modeDetail: Boolean = false
) {
   res: workflow_admin_documents(
     nav: $nav
   ) {
     info {
       ...QueryInfo
     }
     nodes {
       ...WorkflowDocumentAdmin
     }
   }
}


