#import "../fragment/Entity.gql"

query(
   $id: Int,
   $nav: QueryNavInput,
   $modeDetail: Boolean = true
) {
   res: workflow_admin_document(
     id: $id,
     nav: $nav
   ) {
     ...WorkflowDocumentAdmin
   }
}


