#import "@tgin/review/core/gql/fragments/Review.gql"
#import "@tgin/main/graphql/fragment/QueryInfo.gql"

query(
    $filter: ReviewElementFilter,
    $nav: QueryNavInput = {},
    $elementInclude: Boolean = false,
    $elementDetail: Boolean = false
)
{
    res: review_pub_recordset(filter: $filter, nav: $nav) {
        nodes {
            ...Review
        }
        info {
            ...QueryInfo
        }
    }
}
