#import "~module/edu-org/modules/admission/gql/fragment/EduAdmission.gql"
#import "~module/edu-org/modules/source/gql/fragment/EduSource.gql"

fragment EduAisEntrantAchievement on EduAisEntrantAchievement {
   id
   name
   cpriemachievement
   ball
}


