#import "../fragment/ProductElementAdmin.gql"
#import "@tgin/main/graphql/fragment/QueryInfo.gql"

query(
    $iblock: Int,
    $filter: ProductElementFilter,
    $where: Json,
    $nav: QueryNavInput,
    $elementDetail: Boolean = false
) {
    res: catalog_admin_products_recordset(
        iblock: $iblock,
        filter: $filter,
        where: $where,
        nav: $nav
    ) {
        info {
            ...QueryInfo
        }
        nodes {
            ...ProductElementAdmin
        }
    }
}


