#import "../fragment/EduAchievementStatus.gql"
#import "../fragment/EduAchievementType.gql"

query {
    edu_achievement__types: edu_achievement_types {
        ...EduAchievementType
    }

    edu_achievement__statuses: edu_achievement_statuses {
        ...EduAchievementStatus
    }
}



