#import "@tgin/logger/core/gql/event/fragment/Event.gql"

query(
    $filter: LoggerEventFilter,
    $detail: Boolean = true
) {
    res: logger_admin_event(
        filter: $filter
    ) {
        ...LoggerEvent
    }
}
