#import "../fragment/MoodleEntrant.gql"


query(
    $ids: [String],
    $nids: [Int],
    $filter: JSON,
    $nav: QueryInputNav
) {
    res: edu_order_admin_moodle_recordset(
        ids: $ids,
        nids: $nids,
        filter: $filter,
        nav: $nav
    ) {
        ...MoodleEntrant
    }
}


