#import "../fragment/FavAdmin.gql"
#import "@tgin/main/graphql/fragment/QueryInfo.gql"

query(
    $filter: CatalogFavFilter,
    $where: Json,
    $nav: QueryNavInput
) {
    res: catalog_admin_fav_recordset(
        filter: $filter,
        where: $where,
        nav: $nav
    ) {
        info {
            ...QueryInfo
        }
        nodes {
            ...CatalogFavAdmin
        }
    }
}


