#import "../fragment/EventAdmin.gql"
#import "@tgin/main/graphql/fragment/QueryInfo.gql"

query(
    $filter: MailEventFilter,
    $nav: QueryNavInput,
    $detail: Boolean = false
) {
    res: mail_admin_event_recordset(
        filter: $filter,
        nav: $nav
    ) {
        info {
            ...QueryInfo
        }
        nodes {
            ...MailEventAdmin
        }
    }
}


