#import "./AbitTest.gql"
#import "~module/edu-org/modules/subject/gql/fragment/EduSubject.gql"

fragment AbitTestDetail on AbitTest {
    ...AbitTest
    subject {
        ...EduSubject
    }
    order {
        uid
        fio
        ratingId
        snils
    }
}

