
fragment OrderPropDetail on OrderProp {
  ID
  NAME
  CODE
  GROUP_ID
  PERSON_TYPE_ID
  TYPE
  ROLE
  DESC
  PARAMS

  IS_PROFILE
  IS_REQUIRED
  IS_PROFILE_NAME
  IS_UTIL
  IS_READONLY

  PROFILE_TEASER_HIDE

  OPTIONS {
    ID
    NAME
    VALUE
    DESCRIPTION
  }

  COMPONENT_NAMES
  DEFAULT_VALUE
}

