#import "../../basket/fragments/BasketItem.gql"

fragment OrderTeaser on Order {
    ID
    ACCOUNT_NUMBER
    URL
    ACCESS_HASH

    DATE_INSERT
    DATE_UPDATE
    DATE_FORMATTED

    STATUS_ID
    STATUS_NAME
    STATUS_COLOR

    CSTATUS_ID
    CSTATUS_NAME
    CSTATUS_COLOR

    PRICE

    BASKET {
        ...BasketItem
    }

    IS_PAID
    IS_ACTIVE
    IS_CANCELED
    IS_FINISHED
    IS_CAN_PAY
    IS_CAN_PAY_ONLINE
    IS_CAN_PAY_BILL
}

