#import "@tgin/sale/core/gql/order/fragments/OrderTeaser.gql"

query(
    $nav: QueryNavInput = {},
    $filter: OrderFilter = {}
)
{
    res: sale_pub_order_list(filter: $filter, nav: $nav) {
        ...OrderTeaser
    }
}
