#import "@tgin/sale/core/gql/order/fragments/OrderProp.gql"
#import "@tgin/sale/core/gql/vorder/fragments/VorderFields.gql"

fragment VorderAdmin on Vorder {
  ID
  SESSION_ID
  FUSER_ID
  USER_ID
  USER {
    ID
    NAME_FULL
    LOGIN
  }
  ORDER_ID
  ORDER {
    ID
    ACCOUNT_NUMBER
    STATUS_ID
    STATUS_NAME
    STATUS_COLOR
  }
  PRICE
  PROPS {
    ...OrderProp
  }
  FIELDS {
    ...VorderFields
  }
  ACTIONS
}
