
fragment DeliveryZoneElement on DeliveryZoneElement {
  ID
  CODE
  NAME
  URL
  PREVIEW_TEXT
  PROP_PRICE_TEXT
  PROP_PRICE_BY_DELIVERY
  PROP_PRICE_BY_KM
  PROP_FREE_TEXT
  PROP_FREE_FROM_PRICE
  PROP_GEOJSON
  PROP_OUTSIDE
}


