#import "../fragment/EduAisMessage.gql"
#import "@tgin/main/graphql/fragment/QueryInfo.gql"

query(
   $filter: JSON,
   $where: JSON,
   $nav: QueryInputNav
) {
   res: edu_ais_message_listRecordset(
      filter: $filter,
      where: $where,
      nav: $nav
   ) {
     info {
       ...QueryInfo
     }
     nodes {
       ...EduAisMessage
     }
   }
}


