#import "../fragment/EduEpguTaskTeaser.gql"
#import "~module/main/gql/fragments/QueryInfo.gql"

query(
   $filter: JSON,
   $nav: QueryInputNav
) {
   res: edu_epgu_task_listRecordset(filter: $filter, nav: $nav) {
     info {
       ...QueryInfo
     }
     nodes {
       ...EduEpguTaskTeaser
     }
   }
}


