#import "../fragment/EduAdmission.gql"
#import "@tgin/main/graphql/fragment/QueryInfo.gql"

query(
   $filter: JSON,
   $nav: QueryInputNav
) {
   res: edu_admission_recordset(filter: $filter, nav: $nav) {
     info {
       ...QueryInfo
     }
     nodes {
       ...EduAdmission
     }
   }
}


