#import "./BasketItemElement.gql"

fragment BasketItem on BasketItem {
  ID
  NAME
  ORDER_ID
  PRODUCT_ID
  QUANTITY
  PRICE
  PRICE_BASE
  FINAL_PRICE
  FINAL_PRICE_BASE
  MEASURE_NAME
  COMMENT
  ELEMENT {
    ...BasketItemElement
    PARENT {
      ...BasketItemElement
    }
  }
  PROPS {
    NAME
    CODE
    VALUE
    XML_ID
  }
  INPUT_PROPS_HASH
}


