fragment MailEvent on MailEvent {
    ID
    EVENT_NAME
    MESSAGE_ID
    FIELDS @include(if: $detail)
    DATE_INSERT
    DATE_EXEC
    SUCCESS_EXEC
    EVENT {
        ID
        EVENT_NAME
        NAME
    }

    USER_ID
    USER {
        ID
        LOGIN
    }

    ORDER_ID
    ORDER {
        ID
        ACCOUNT_NUMBER
        USER_ID
        USER {
            ID
            LOGIN
        }
    }

    ACTIONS
}

