#import "../fragment/EduAisEntrant.gql"
#import "@tgin/main/graphql/fragment/QueryInfo.gql"

query(
   $filter: JSON,
   $nav: QueryInputNav
) {
   res: edu_aisEntrant_recordset(filter: $filter, nav: $nav) {
     info {
       ...QueryInfo
     }
     nodes {
       ...EduAisEntrant
     }
   }
}


