
export enum AbitOrderStatusEnum {
    CANDIDATE = 'candidate',
    DRAFT = 'draft',
    SENDED = 'sended',
    FIX_APPS = 'fix_apps',
    FIX_ANKET = 'fix_anket',
    SENDED_FIXED = 'sended_fixed',
    ACCEPTED = 'accepted',
    CANCELED = 'canceled',
    CANCELED_ORG = 'canceled_org',
    DUPLICATE = 'duplicate',
    INORDER = 'inorder',
    STUDENT = 'student'
}

export const abitOrderStatusList = [
    {
        code: AbitOrderStatusEnum.CANDIDATE,
        titleClient: 'Кандидат',
        titleAdmin: 'Кандидат',
        bgColor: '#bd892a',
        textColor: '#ffffff',
        color: '#bd892a',
        index: 1,
        canEdit: false,
        selectable: true,
        member: false,
        aisStatusId: 4
    },
    {
        code: AbitOrderStatusEnum.DRAFT,
        titleClient: 'Черновик',
        titleAdmin: 'Черновик',
        bgColor: '#eeeeee',
        textColor: '#111111',
        color: '#111111',
        index: 1,
        canEdit: true,
        selectable: true,
        member: false,
        aisStatusId: 4
    },
    {
        code: AbitOrderStatusEnum.SENDED,
        titleClient: 'Отправлено в ИРНИТУ: ожидает рассмотрения',
        titleAdmin: 'Ожидает рассмотрения',
        bgColor: '#eebc00',
        textColor: '#ffffff',
        color: '#d5ad00',
        index: 3,
        canEdit: false,
        selectable: true,
        member: false,
        aisStatusId: 2
    },
    {
        code: AbitOrderStatusEnum.FIX_APPS,
        titleClient: 'Возвращено на корректировку направлений',
        titleAdmin: 'Корректировка направлений',
        bgColor: '#ee4822',
        textColor: '#ffffff',
        color: '#ee4822',
        index: 4,
        canEdit: ['applications', 'upload', 'send'],
        selectable: true,
        member: false,
        aisStatusId: 2
    },
    {
        code: AbitOrderStatusEnum.FIX_ANKET,
        titleClient: 'Возвращено на корректировку анкеты',
        titleAdmin: 'Корректировка анкеты',
        bgColor: '#ee4822',
        textColor: '#ffffff',
        color: '#ee4822',
        index: 5,
        canEdit: ['anket', 'applications', 'upload', 'send'],
        selectable: true,
        member: false,
        aisStatusId: 2
    },
    {
        code: AbitOrderStatusEnum.SENDED_FIXED,
        titleClient: 'Отправлено в ИРНИТУ: Ожидает рассмотрения',
        titleAdmin: 'Повтор: Ожидает рассмотрения',
        bgColor: '#eebc00',
        textColor: '#ffffff',
        color: '#eebc00',
        index: 6,
        canEdit: false,
        member: false,
        aisStatusId: 2
    },
    {
        code: AbitOrderStatusEnum.ACCEPTED,
        titleClient: 'Принято: Участвует в конкурсе',
        titleAdmin: 'Принято: Участвует в конкурсе',
        bgColor: '#1ca834',
        textColor: '#ffffff',
        color: '#1ca834',
        index: 7,
        canEdit: false,
        selectable: true,
        member: true,
        aisStatusId: 2
    },
    {
        code: AbitOrderStatusEnum.CANCELED,
        titleClient: 'Отозвано: Не участвует в конкурсе',
        titleAdmin: 'Отозвано: Не участвует в конкурсе',
        bgColor: '#ee4822',
        textColor: '#ffffff',
        color: '#ee4822',
        index: 8,
        canEdit: false,
        selectable: true,
        canceled: true,
        aisStatusId: 2
    },
    {
        code: AbitOrderStatusEnum.CANCELED_ORG,
        titleClient: 'Отклонено ВУЗом',
        titleAdmin: 'Отклонено ВУЗом',
        bgColor: '#ee4822',
        textColor: '#ffffff',
        color: '#ee4822',
        index: 9,
        canEdit: false,
        selectable: true,
        canceled: true,
        aisStatusId: 2
    },
    {
        code: AbitOrderStatusEnum.DUPLICATE,
        titleClient: 'Дубль',
        titleAdmin: 'Дубль',
        bgColor: '#ee4822',
        textColor: '#ffffff',
        color: '#ee4822',
        index: 12,
        canEdit: false,
        selectable: true,
    },
    {
        code: AbitOrderStatusEnum.INORDER,
        titleClient: 'Зачислен',
        titleAdmin: 'Зачислен',
        bgColor: '#1458c2',
        textColor: '#ffffff',
        color: '#1458c2',
        index: 13,
        canEdit: false,
        selectable: false,
        aisStatusId: 14
    },
    {
        code: AbitOrderStatusEnum.STUDENT,
        titleClient: 'Студент',
        titleAdmin: 'Студент',
        bgColor: '#1458c2',
        textColor: '#ffffff',
        color: '#1458c2',
        index: 14,
        canEdit: false,
        selectable: false,
        aisStatusId: 1
    },
]

export const abitOrderStatusListById = abitOrderStatusList.reduce((map, o) => (map[o.code] = o, map), {})
