
fragment VorderReserve on VorderReserve {
  ID
  VORDER_ID
  DEPARTMENT_ID
  DEPARTMENT {
    ID
    CID
    NAME
  }

  NEED_NEAREST
  NEED_DELTA
  REQUEST_DELTA

  DATE_REQUEST
  DATE_NEED
  DATE_SUGGESTED

  DATE_REQUEST_FORMATTED
  DATE_NEED_FORMATTED
  DATE_SUGGESTED_FORMATTED
}

