#import "@tgin/sale/core/gql/basket/fragments/Basket.gql"

query(
  $vorderInclude: Boolean = false,
  $recalc: Boolean = false
)
{
  res: sale_pub_basket_state(recalc: $recalc) {
    ...Basket
  }
}
