#import "@tgin/sale/core/gql/basket/fragments/Basket.gql"
#import "@tgin/sale/core/gql/order/fragments/PersonType.gql"
#import "@tgin/sale/core/gql/fav/fragments/FavItem.gql"

query(
    $vorderInclude: Boolean = false
) {
    sale_pub__basket: sale_pub_basket_state {
        ...Basket
    }
    sale_pub__favs: sale_pub_fav_state {
        ...FavItem
    }
    sale_pub__personTypes: sale_pub_person_types {
        ...PersonType
    }
}
