#import "../fragments/MenuItem.gql"

query {
   menu__menus: menu_menus {
     ...MenuItem
     children {
        ...MenuItem
        children {
           ...MenuItem
           children {
              ...MenuItem
              children {
                 ...MenuItem
              }
           }
        }
     }
   }
}

