#import "../../../core/gql/product/fragments/ProductElement.gql"
#import "../../../core/gql/product/fragments/ProductSectionBase.gql"

query(
    $query: String,
    $elementDetail: Boolean = false
)
{
    res: catalog_search(query: $query) {
        ELEMENTS {
            ...ProductElement
        }
        SECTIONS {
            ...ProductSectionBase
        }
    }
}
