fragment ProductSectionBase on ProductSection {
    ID
    NAME
    CODE
    URL
    ELEMENT_CNT
    REPLACE_LINK

    PICTURE {
        SRC
    }

    META {
        TITLE
        DESCRIPTION
        KEYWORDS
    }
}


