#import "../fragments/Office.gql"
#import "../fragments/Contact.gql"

query (
  $filter: CompanyOfficeFilter
)
{
  res: company_offices(filter: $filter) {
    nodes {
      ...CompanyOffice
      CONTACT_ELEMENTS {
        ...CompanyContact
      }
    }
  }
}

