#import "../../order/fragments/OrderPropDetail.gql"
#import "../../order/fragments/OrderPropValue.gql"

fragment OrderProfile on OrderProfile {
    ID
    NAME
    CAPTION
    USER_ID
    PERSON_TYPE_ID
    PERSON_TYPE {
        ID
        NAME
        IS_COMPANY
    }
    COMPANY_ID
    COMPANY {
        ID
        NAME
    }
    PROPS @include(if: $profileDetail) {
        ...OrderPropValue
        PROP {
            ...OrderPropDetail
        }
    }
}
